In [2]:
%pip install mlxtend

Collecting mlxtend
  Downloading mlxtend-0.25.0-py3-none-any.whl.metadata (7.4 kB)
Requirement already satisfied: scipy>=1.16.3 in /Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages (from mlxtend) (1.17.1)
Requirement already satisfied: numpy>=2.3.5 in /Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages (from mlxtend) (2.4.4)
Requirement already satisfied: pandas>=2.3.3 in /Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages (from mlxtend) (3.0.2)
Requirement already satisfied: scikit-learn>=1.8.0 in /Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages (from mlxtend) (1.8.0)
Requirement already satisfied: matplotlib>=3.10.8 in /Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages (from mlxtend) (3.10.8)
Requirement already satisfied: joblib>=1.5.2 in /Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages (from mlxtend) (1.5.3)
Requirement already satisfied: contourpy>=1.0.1 in /Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages (from matplotlib>=3.10.8->mlxtend) (1.3.3)
Requirement already satisfied: cycler>=0.10 in /Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages (from matplotlib>=3.10.8->mlxtend) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages (from matplotlib>=3.10.8->mlxtend) (4.62.1)
Requirement already satisfied: kiwisolver>=1.3.1 in /Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages (from matplotlib>=3.10.8->mlxtend) (1.5.0)
Requirement already satisfied: packaging>=20.0 in /Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages (from matplotlib>=3.10.8->mlxtend) (26.1)
Requirement already satisfied: pillow>=8 in /Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages (from matplotlib>=3.10.8->mlxtend) (12.2.0)
Requirement already satisfied: pyparsing>=3 in /Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages (from matplotlib>=3.10.8->mlxtend) (3.3.2)
Requirement already satisfied: python-dateutil>=2.7 in /Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages (from matplotlib>=3.10.8->mlxtend) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in /Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages (from python-dateutil>=2.7->matplotlib>=3.10.8->mlxtend) (1.17.0)
Requirement already satisfied: threadpoolctl>=3.2.0 in /Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages (from scikit-learn>=1.8.0->mlxtend) (3.6.0)
Downloading mlxtend-0.25.0-py3-none-any.whl (1.4 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.4/1.4 MB 2.6 MB/s  0:00:00m 2.6 MB/s eta 0:00:01
Installing collected packages: mlxtend
Successfully installed mlxtend-0.25.0

[notice] A new release of pip is available: 26.0.1 -> 26.1.2
[notice] To update, run: pip3 install --upgrade pip
Note: you may need to restart the kernel to use updated packages.

In [4]:
import pandas as pd
from mlxtend.frequent_patterns import apriori, association_rules

In [5]:
import pandas as pd
from mlxtend.frequent_patterns import apriori, association_rules

In [6]:
import os
os.getcwd()

'/Users/alancastellanos'

In [7]:
import os
os.listdir()

['Downloads.sb-14d7899f-evUjqk',
 'Downloads.sb-14d7899f-OmKIjC',
 'Downloads.sb-c02e82f6-muWfF4',
 'Downloads.sb-dfae817a-zF4H4u',
 'RestaurantFranchiseChart .xlsx',
 'Music',
 'EJBTable.xlsx',
 'Downloads.sb-c02e82f6-ep3buy',
 'products.csv',
 'Untitled5.ipynb',
 'sales+data.csv',
 'Downloads.sb-14d7899f-MLB4OZ',
 'Downloads.sb-14d7899f-Fw3EWP',
 'Untitled1.ipynb',
 'Umbrella.xlsx',
 'Downloads.sb-c02e82f6-aqM3xo',
 'Downloads.sb-c02e82f6-w3Cp33',
 'Downloads.sb-dfae817a-d9Hs86',
 'Experimental_Analysis_SQL_Python.ipynb',
 'customers+%281%29.csv',
 '.DS_Store',
 'Downloads.sb-14d7899f-ApRTBq',
 'nltk_data',
 'ARFData.xlsx',
 '.CFUserTextEncoding',
 'customer_reviews module 7.csv',
 'customer_reviews.db',
 'cleaned_purchases.csv',
 'F500MetrosChart.xlsx',
 'cleaned_customers.csv',
 'Untitled3.ipynb',
 'anomaly_detection.db',
 'Downloads.sb-c02e82f6-N5gKcr',
 'Module 2 Critical Thinking data&SQL',
 'Text_Analysis_SQL_Python_Assignment.ipynb',
 'Untitled.ipynb',
 'Downloads.sb-c02e82f6-v93T1u',
 'Downloads.sb-c02e82f6-1HK89S',
 'MIS415_CT2_schema.txt',
 'Downloads.sb-14d7899f-68H738',
 'Untitled4.ipynb',
 'Downloads.sb-14d7899f-98Kkkq',
 'Pictures',
 '.zprofile',
 'transactions+%281%29.csv',
 'transactions Module 8.csv',
 '.zsh_history',
 'products module 8.csv',
 'Untitled2.ipynb',
 '.ipython',
 'Desktop',
 'Library',
 '.matplotlib',
 'MajorSalary.xlsx',
 'Downloads.sb-dfae817a-5jGx7a',
 'TimeSeries_SQL_Python_Assignment.ipynb',
 'Cosmetics.csv',
 'module8.db',
 'Parallels',
 'sales_assignment.db',
 'Cats^126Dogs.xlsx',
 'Downloads.sb-c02e82f6-RLbunZ',
 'AttendWinsChart .xlsx',
 'PrimeTimeXFL.xlsx',
 'products-1 module 7.csv',
 'Downloads.sb-14d7899f-SYTeZs',
 'Public',
 'Your Beneficiaries.pdf',
 'Downloads.sb-14d7899f-QNxICH',
 'Downloads.sb-14d7899f-Je5IPG',
 '.idlerc',
 'Downloads.sb-14d7899f-YfmZ4x',
 'Module8_SQL_Python_Ecommerce_Analysis.ipynb',
 'Downloads.sb-c02e82f6-2tsVln',
 'F500MetrosChart copy.xlsx',
 'Module 6 Anomaly Detection SQL Python.ipynb',
 'Module2CTA.ipynb',
 'Applications (Parallels)',
 'Movies',
 'Applications',
 'Module_4_Cohort_Analysis.ipynb',
 '.Trash',
 'Downloads.sb-14d7899f-COrkik',
 'Downloads.sb-dfae817a-6jzo7c',
 '.ipynb_checkpoints',
 'Downloads.sb-dfae817a-GrKPzw',
 '.jupyter',
 'Downloads.sb-14d7899f-q21uhb',
 'Documents',
 'Downloads.sb-dfae817a-OXVaVF',
 'Module 8 Potafolio Project.xlsx',
 'Example_Dataset_25Rows.csv',
 'Downloads.sb-14d7899f-WLhluZ',
 'Websites.xlsx',
 'Downloads.sb-14d7899f-KVJU20',
 'Downloads.sb-c02e82f6-g4zOaQ',
 'Downloads.sb-c02e82f6-oSc4Jo',
 'product_reviews.csv',
 'Downloads',
 'sales.db',
 'Downloads.sb-14d7899f-Th70Er',
 'DayTradingChart.xlsx',
 'Downloads.sb-dfae817a-79ZEIN',
 'Downloads.sb-dfae817a-vlxg2J',
 'Downloads.sb-14d7899f-3j0ufG',
 'Downloads.sb-dfae817a-GaV9q4',
 '.zsh_sessions',
 'Downloads.sb-14d7899f-RBO4BJ',
 'HolidayGrassChart .xlsx',
 'Unemployment Rate Exploratory Analysis Using SAS.docx',
 'Downloads.sb-14d7899f-kcYzXW',
 'Downloads.sb-14d7899f-b1qGZy']

In [8]:
os.listdir("/Users/alancastellanos/Downloads")

['Alan_Castellanos_Logistic_Regression_Assignment_APA7.docx',
 'googlechrome.dmg',
 'Act IMG_1394.pdf',
 'IMG_3883 2.HEIC',
 '31-SouthAfricaMayans.pptx',
 '35PP-JapanMongols.pptx',
 '38PP-CrusadesChivalryPlague.pptx',
 'IMG_0246.heic',
 'Outlook-hasjguvw 2',
 'English Introduction (2).docx',
 'Presentation.Chapter 13_revised_12th_edition-1.pptx',
 'English Introduction.pdf',
 'IMG_0765.heic',
 '~$x Website Editor _ Field Representative.mhtml',
 'BIO 1510 01 General Biology Syl  Spring 2025-5.doc',
 'ReportOption3 (2).docx',
 'bank.csv',
 'Exam3Overview.docx',
 'products.csv',
 '38-ReviewChristendom (1).pptx',
 'sales+data.csv',
 'IMG_2373.heic',
 'mysql-9.6.0-macos15-arm64.dmg',
 'googlechrome-4.dmg',
 'Alan Castellanos-College Resume .pdf',
 'products-2+%281%29.csv',
 'Website Editor _ Field Representative_files',
 'IMG_2372.heic',
 'customers+%281%29.csv',
 '.DS_Store',
 'ch_03_Lecture_Presentation_ADA.pdf',
 'Primary_Source_Analysis_Report-1728722543000 (3).docx',
 '36PP-Mongols.pptx',
 'Castellanos_Alan_1199033_12_13_2024.pdf',
 'Module_4_Cohort_Analysis.py',
 'ARFData.xlsx',
 'AC.pdf',
 '33-IncasChina.pptx',
 'Wix Website Editor _ Field Representative.pdf',
 'UNRATE.xls',
 'IMG_3884.HEIC',
 'googlechrome-3.dmg',
 'Date_Table 2.csv',
 'text-401B-A2D6-C7-0.txt',
 'ReportOption3.docx',
 'customer_reviews.csv',
 'IMG_0542ACDF22F5-1.jpeg',
 'Ch. 1 - Evolution, the Themes of Biology, and Scientific Inquiry.pdf',
 'Website Editor _ Field Representative.html',
 'cleaned_purchases.csv',
 'Primary_Source_Analysis_Report-1728722543000 (1).docx',
 'Outlook-q41vwuok',
 'Date_Table 3.csv',
 '.localized',
 'cleaned_customers.csv',
 'Default.csv',
 'Alan_Ingredient_Matrix copy.docx',
 'googlechrome-2.dmg',
 'Detection (1s1).exe',
 'Text_Analysis_SQL_Python_Assignment.ipynb',
 'English Introduction (1).docx',
 'Untitled.ipynb',
 'IMG_0513.jpg',
 'Alan_Castellanos_Logistic_Regression_Assignment_APA7 2.docx',
 'transactions-1+%282%29.csv',
 'IMG_1021.heic',
 'Personal Statement Form.pdf',
 '$RECYCLE.BIN',
 '29-EarlyWestAfrica.pptx',
 'mysql-workbench-community-8.0.46-macos-arm64.dmg',
 'ch_05_Lecture_Presentation_ADA.pdf',
 'IMG_0512.jpg',
 'English Introduction.docx',
 'Unknown.pdf',
 'text-BEEF1C842AA0-1.txt',
 'Primary_Source_Analysis_Report-1728722543000 (4).docx',
 '30-WestAfricaEastSouth.pptx',
 'IMG_0698.PNG',
 'winequality-red.csv',
 'ReportOption3 (1).docx',
 'IMG_3883.HEIC',
 'Headshot.pdf',
 'transactions+%281%29.csv',
 'IMG_0529.jpg',
 'IMG_0515.jpg',
 'Module 1 Critical Thinking.pdf',
 'Ch. 3 The Cell_ The Fundamental Unit of Life.pdf',
 'Date_Table.csv',
 'ch_05_Lecture_Presentation_ADA.pptx',
 'IMG_0514.jpg',
 '28-IslamSpreadWestAfrica (1).pptx',
 'IMG_0714.jpg',
 'Primary_Source_Analysis_Report-1728722543000 (2).docx',
 'Text_Analysis_SQL_Python_Assignment-2.ipynb',
 'Cosmetics.csv',
 'IMG_1394.HEIC.zip',
 'annotated-Informative%20Speech%20Topics.pdf',
 'zip.txt',
 'OneDrive_1_12-9-2024',
 'IMG_2372 2.heic',
 'PSY 2010-03 General Psychology Spring 2025.docx',
 'IMG_1020.heic',
 'ch_06_Lecture_Presentation_ADA.pdf',
 'Microscopes-worksheet.pdf',
 'ENG-1010L-01 Syllabus Spring 2025-2.pdf',
 'worksheet_2287.pdf',
 '~$sample Superstore 2.xlsx',
 'Mac Install MyEducator Addin.xlsm',
 'Presentation.Chapter 7_revised_12th_edition.pptx',
 'sample Superstore 3.xlsx',
 'Electron Microscopy.jpeg',
 'Wix Website Editor _ Field Representative.mhtml',
 'OneDrive_1_12-9-2024.zip',
 'sample Superstore 3.xlsx.zip',
 'ChatGPT Image May 25, 2025, 08_29_48 AM.png',
 'regulation_lactase_gene_click_learn_worksheet.pdf',
 '39-ChivalryPlagueWar.pptx',
 'Sales_Table 3.csv',
 'Sales_Table 2.csv',
 'sales+data week3 .csv',
 'IMG_1049 2.heic',
 'ymr5vl_670f174fb04a01_29044173.docx',
 'primary_source_analysis_report_1728722543000_17340021552191734011664389-1_1734025424467.docx',
 'mushrooms_dataset+%281%29.xlsx',
 'sample Superstore.xlsx',
 'description-winequality-red.docx',
 '34PP-MedievalChina.pptx',
 'ENG-1010L-01 Syllabus Spring 2025-2 (1).pdf',
 'ch_04_Lecture_Presentation_ADA.pdf',
 '~$wordchoice.ppt',
 'Module 6 Anomaly Detection SQL Python.ipynb',
 '40-PlagueWarRenassaince.pptx',
 'ReportEXAMPLE (2).docx',
 '32-MayansIncasAztec.pptx',
 'ReportEXAMPLE.docx',
 'Exam 1 and 2 .pdf',
 'IMG_0682.PNG',
 'Tax return 3.pdf',
 'sample Superstore 2.xlsx',
 'Tax return 2.pdf',
 'Module_4_Cohort_Analysis.ipynb',
 'IMG_0246.pdf',
 '~$sample Superstore 3.xlsx',
 '38-ReviewChristendom.pptx',
 'wordchoice.ppt',
 'Exam 1 and 2  2.pdf',
 '33-IncasChina (1).pptx',
 'IMG_0720.jpg',
 'Portfolio Project: Comprehensive Data Visualization Using Power BI.docx',
 'Critical_Thinking_Assignment_PowerBI.docx',
 'PBIDesktopSetup_x64.exe',
 'Sales_Table.csv',
 'IMG_1049.jpg',
 'IMG_1394.HEIC',
 'IMG_3884 2.HEIC',
 'BIO+1510+01+General+Biology+Syl++Spring+2025 3.doc',
 'IMG_0141.jpg',
 '28-IslamSpreadWestAfrica.pptx',
 'INT 0960 SP25 Syllabus-1.docx',
 '~$sample Superstore.xlsx',
 'IMG_0140.jpg',
 'BIO+1510+01+General+Biology+Syl++Spring+2025 2.doc',
 'BIO+1510+01+General+Biology+Syl++Spring+2025.doc',
 'desktop.ini',
 'PSY 2010-03 General Psychology Spring 2025 (1).docx',
 'Install Parallels Desktop-bg71hays.dmg',
 'SuperstoreDataset.zip',
 'postgresql-18.4-2-windows-x64.exe',
 '0-6_ Submit - Orientation Activity_ Introducing Yourself and Reflecting on Big Ideas!.pdf',
 'BUS 2010 02 -  Spring 25.doc',
 'Presentation.Chapter 13_revised_12th_edition.pptx',
 'Websites.xlsx',
 'IMG_0142.jpg',
 'Primary_Source_Analysis_Report-1728722543000.docx',
 'product_reviews.csv',
 'IMG_1049.pdf',
 'Portfolio_Milestone_APA.docx',
 'Outlook-hasjguvw',
 'Wix Website Editor _ Field Representative.html',
 'IMG_1049.heic',
 'IMG_2373 2.heic',
 'IMG_1675.heic',
 'Tax return.pdf',
 'ENGL 1010-03 - MWF 0100 - Course Syllabus.pdf',
 'annotated-Primary_Source_Analysis_Report-1728722543000.docx.pdf',
 '33-IncasChina (2).pptx',
 'products-1.csv',
 'Confirmation Lunch Reduction .pdf',
 'Castellanos_Alan_1199033_12_16_2024.pdf',
 'ReportEXAMPLE (1).docx',
 'Picture .pdf',
 'Presentation.Chapter 13_revised_12th_edition-2.pptx']

In [9]:
basket = pd.read_csv("/Users/alancastellanos/Downloads/Cosmetics.csv")
basket.head()

,Bag,Blush,Nail Polish,Brushes,Concealer,Eyebrow Pencils,Bronzer,Lip liner,Mascara,Eye shadow,Foundation,Lip Gloss,Lipstick,Eyeliner
0,0,1,1,1,1,0,1,1,1,0,0,0,0,1
1,0,0,1,0,1,0,1,1,0,0,1,1,0,0
2,0,1,0,0,1,1,1,1,1,1,1,1,1,0
3,0,0,1,1,1,0,1,0,0,0,1,0,0,1
4,0,1,0,0,1,0,1,1,1,1,0,1,1,0

In [10]:
frequent_items = apriori(
    basket.astype('bool'),
    min_support=0.02,
    use_colnames=True
)

frequent_items.head()

   support                  itemsets
0    0.054          frozenset({Bag})
1    0.363        frozenset({Blush})
2    0.280  frozenset({Nail Polish})
3    0.149      frozenset({Brushes})
4    0.442    frozenset({Concealer})

In [11]:
frequent_items

      support                                           itemsets
0       0.054                                   frozenset({Bag})
1       0.363                                 frozenset({Blush})
2       0.280                           frozenset({Nail Polish})
3       0.149                               frozenset({Brushes})
4       0.442                             frozenset({Concealer})
...       ...                                                ...
1458    0.020  frozenset({Bronzer, Foundation, Eyeliner, Conc...
1459    0.022  frozenset({Bronzer, Brushes, Lip liner, Concea...
1460    0.021  frozenset({Bronzer, Eyeliner, Brushes, Conceal...
1461    0.021  frozenset({Bronzer, Foundation, Lip liner, Con...
1462    0.021  frozenset({Bronzer, Eyeliner, Brushes, Lip lin...

[1463 rows x 2 columns]

In [12]:
rules = association_rules(
    frequent_items,
    metric="confidence",
    min_threshold=0.5
)

rules.head()

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,representativity,leverage,conviction,zhangs_metric,jaccard,certainty,kulczynski
0,frozenset({Bag}),frozenset({Blush}),0.054,0.363,0.032,0.592593,1.632486,1.0,0.012398,1.563545,0.409553,0.083117,0.360428,0.340373
1,frozenset({Bag}),frozenset({Nail Polish}),0.054,0.280,0.028,0.518519,1.851852,1.0,0.012880,1.495385,0.486258,0.091503,0.331276,0.309259
2,frozenset({Bag}),frozenset({Concealer}),0.054,0.442,0.035,0.648148,1.466399,1.0,0.011132,1.585895,0.336213,0.075922,0.369441,0.363667
3,frozenset({Bag}),frozenset({Mascara}),0.054,0.357,0.038,0.703704,1.971159,1.0,0.018722,2.170125,0.520808,0.101877,0.539197,0.405073
4,frozenset({Bag}),frozenset({Eye shadow}),0.054,0.381,0.032,0.592593,1.555361,1.0,0.011426,1.519364,0.377445,0.079404,0.341830,0.338291

In [13]:
rules.sort_values(by='confidence', ascending=False)

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,representativity,leverage,conviction,zhangs_metric,jaccard,certainty,kulczynski
2570,"frozenset({Brushes, Eye shadow, Blush, Eyeliner})",frozenset({Mascara}),0.026,0.357,0.026,1.0,2.801120,1.0,0.016718,inf,0.660164,0.072829,1.000000,0.536415
4651,"frozenset({Bronzer, Lip liner, Foundation, Eye...",frozenset({Lip Gloss}),0.025,0.490,0.025,1.0,2.040816,1.0,0.012750,inf,0.523077,0.051020,1.000000,0.525510
9569,"frozenset({Bronzer, Eyeliner, Brushes, Lip lin...",frozenset({Nail Polish}),0.021,0.280,0.021,1.0,3.571429,1.0,0.015120,inf,0.735444,0.075000,1.000000,0.537500
1043,"frozenset({Brushes, Lip liner, Eye shadow})",frozenset({Nail Polish}),0.038,0.280,0.038,1.0,3.571429,1.0,0.027360,inf,0.748441,0.135714,1.000000,0.567857
5936,"frozenset({Bronzer, Eyeliner, Lip liner, Masca...",frozenset({Concealer}),0.025,0.442,0.025,1.0,2.262443,1.0,0.013950,inf,0.572308,0.056561,1.000000,0.528281
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3480,"frozenset({Brushes, Bronzer, Nail Polish, Eye ...",frozenset({Foundation}),0.054,0.536,0.027,0.5,0.932836,1.0,-0.001944,0.928,-0.070727,0.047957,-0.077586,0.275187
3414,"frozenset({Brushes, Lip liner})","frozenset({Bronzer, Nail Polish, Eye shadow})",0.068,0.070,0.034,0.5,7.142857,1.0,0.029240,1.860,0.922747,0.326923,0.462366,0.492857
3412,"frozenset({Brushes, Nail Polish, Lip liner})","frozenset({Bronzer, Eye shadow})",0.068,0.141,0.034,0.5,3.546099,1.0,0.024412,1.718,0.770386,0.194286,0.417928,0.370567
3364,"frozenset({Brushes, Eyeliner})","frozenset({Nail Polish, Concealer, Eye shadow})",0.078,0.078,0.039,0.5,6.410256,1.0,0.032916,1.844,0.915401,0.333333,0.457701,0.500000
6495,"frozenset({Lip Gloss, Lip liner, Foundation})","frozenset({Blush, Mascara, Eye shadow})",0.046,0.169,0.023,0.5,2.958580,1.0,0.015226,1.662,0.693920,0.119792,0.398315,0.318047

In [14]:
rules.sort_values(by='lift', ascending=False)

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,representativity,leverage,conviction,zhangs_metric,jaccard,certainty,kulczynski
9963,"frozenset({Brushes, Blush, Lip liner, Eye shad...","frozenset({Bronzer, Nail Polish, Mascara, Conc...",0.024,0.055,0.022,0.916667,16.666667,1.0,0.020680,11.340000,0.963115,0.385965,0.911817,0.658333
9966,"frozenset({Brushes, Lip liner, Mascara, Blush})","frozenset({Bronzer, Nail Polish, Concealer, Ey...",0.026,0.052,0.022,0.846154,16.272189,1.0,0.020648,6.162000,0.963599,0.392857,0.837715,0.634615
10260,"frozenset({Bronzer, Eye shadow, Nail Polish, E...","frozenset({Brushes, Lip liner, Mascara, Concea...",0.038,0.034,0.021,0.552632,16.253870,1.0,0.019708,2.159294,0.975547,0.411765,0.536886,0.585139
10275,"frozenset({Brushes, Lip liner, Mascara, Concea...","frozenset({Bronzer, Eye shadow, Nail Polish, E...",0.034,0.038,0.021,0.617647,16.253870,1.0,0.019708,2.516000,0.971507,0.411765,0.602544,0.585139
9967,"frozenset({Brushes, Blush, Concealer, Eye shad...","frozenset({Bronzer, Nail Polish, Lip liner, Ma...",0.034,0.040,0.022,0.647059,16.176471,1.0,0.020640,2.720000,0.971203,0.423077,0.632353,0.598529
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3954,"frozenset({Bronzer, Nail Polish, Mascara, Eyel...",frozenset({Foundation}),0.042,0.536,0.021,0.500000,0.932836,1.0,-0.001512,0.928000,-0.069903,0.037702,-0.077586,0.269590
3972,"frozenset({Nail Polish, Lip liner, Mascara, Ey...",frozenset({Foundation}),0.044,0.536,0.022,0.500000,0.932836,1.0,-0.001584,0.928000,-0.070039,0.039427,-0.077586,0.270522
1414,"frozenset({Brushes, Bronzer, Eye shadow})",frozenset({Foundation}),0.054,0.536,0.027,0.500000,0.932836,1.0,-0.001944,0.928000,-0.070727,0.047957,-0.077586,0.275187
4662,"frozenset({Lip Gloss, Bronzer, Mascara, Eye sh...",frozenset({Foundation}),0.070,0.536,0.035,0.500000,0.932836,1.0,-0.002520,0.928000,-0.071856,0.061296,-0.077586,0.282649
847,"frozenset({Lip Gloss, Bronzer, Blush})",frozenset({Foundation}),0.072,0.536,0.036,0.500000,0.932836,1.0,-0.002592,0.928000,-0.072000,0.062937,-0.077586,0.283582

In [15]:
rules.to_excel("Association_Rules.xlsx", index=False)

ModuleNotFoundError: No module named 'openpyxl'

In [16]:
%pip install openpyxl

/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/pty.py:66: DeprecationWarning: This process (pid=28170) is multi-threaded, use of forkpty() may lead to deadlocks in the child.
  pid, fd = os.forkpty()

Collecting openpyxl
  Downloading openpyxl-3.1.5-py2.py3-none-any.whl.metadata (2.5 kB)
Collecting et-xmlfile (from openpyxl)
  Downloading et_xmlfile-2.0.0-py3-none-any.whl.metadata (2.7 kB)
Downloading openpyxl-3.1.5-py2.py3-none-any.whl (250 kB)
Downloading et_xmlfile-2.0.0-py3-none-any.whl (18 kB)
Installing collected packages: et-xmlfile, openpyxl
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2/2 [openpyxl]━━ 1/2 [openpyxl]
Successfully installed et-xmlfile-2.0.0 openpyxl-3.1.5

[notice] A new release of pip is available: 26.0.1 -> 26.1.2
[notice] To update, run: pip3 install --upgrade pip
Note: you may need to restart the kernel to use updated packages.

In [17]:
rules.to_excel("Association_Rules.xlsx", index=False)